# Complete hardcoded title -> nickname mapping
# All 95 royalty titles with their nicknames
HARDCODED_TITLE_NICKNAMES = {
    " Basaa  Attic: Le Grenier du Basaa: Ndùgí ì Ɓàsàá": "basaa_attic",
    " Duala  Attic: Le Grenier du Duala: Elombá á Duálá": "duala_attic",
    " Yoruba  Attic: Le Grenier du Yoruba: Òkè Àjà Yorùbá ": "yoruba_attic",
    "African tales, Bamiléké fairy tales, English-French version: Contes africains, contes bamilekes, Anglais-Francais": "english-french_african_tales",
    "Bamilekes Fairy Tales - Work today and eat tomorrow, be lazy today and steal tomorrow: English-French: Happi & Shwinao": "english-french_bamilekes_fairy_tales",
    "Basaa - French - English Phrasebook: Guide de conversation Basaa-Français-Anglais. ": "basaa_phrasebook",
    "Chichewa - French - English Phrasebook: Gawo Loyamba: Guide de conversation Chichewa-Français-Anglais.": "chichewa_phrasebook",
    "Conte Africain - Duala: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».": "duala_conte_travaille_paresse",
    "Conte Africain - Kikongo: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».": "kikongo_conte_travaille_paresse",
    "Conte Africain - Wolof: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».": "wolof_conte_travaille_paresse",
    "Conte Africain -Fongbe: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».": "fongbe_conte_travaille_paresse",
    "Conte Bamileke -Medumba: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».: Medumba-Francais": "medumba_conte_travaille_paresse",
    "Conte Bamileke -Ngiemboon: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».: Ngiemboon-Francais": "ngiemboon_conte_travaille_paresse",
    "Conte Bamileke-Yemba :  « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».": "yemba_conte_travaille_paresse",
    "Conte Bamiléké-Nufi « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».: Version Nufi-Francais": "nufi_conte_travaille_paresse",
    "Conte Camerounais -Ewondo: « Travaille aujourd'hui et mange demain, paresse aujourd'hui et vole demain ».": "ewondo_conte_travaille_paresse",
    "Contes africains, contes bamilekés racontés en nufi et traduits en francais (Full Color): African's fairy tales": "nufi_contes_bamilekés_couleur",
    "Contes africains, contes bamilekés racontés en nufi et traduits en francais: African's fairy tales, bamileke tales": "nufi_contes_bamilekés_RETIRED",
    "Contes africains, contes bamilékés racontés en nufi et traduits en français (Black and White): African's fairy tales": "nufi_contes_bamilekés_black_white",
    "Contes bamilekés racontés en ghomala' et traduits en français (Version Couleur): Bə a la tə pə́ a ? Bə a lə pə̌ ə́.": "ghomala_contes_bamilekés",
    "Contes bamilekés racontés en medumba et traduits en français (Black and White): medumba (Bangangte) Fairy tales": "medumba_contes_bamilekés_black_white",
    "Contes bamilekés racontés en medumba et traduits en français (Version Couleur): medumba fairy tales": "medumba_contes_bamilekés",
    "Contes bamilekés racontés en medumba et traduits en français: medumba (bangante) fairy tales": "medumba_contes_bamilekés_couleur",
    "Contes bamilekés racontés en ngemba et traduits en français: A lə lǎ' mbɔ́ mɔ̀' lěʼ": "ngemba_contes_bamilekés",
    "Contes bamilekés racontés en yemba et traduits en francais": "yemba_contes_bamilekés",
    "Conversation de base en langue ewondo": "ewondo_conversation_de_base",
    "Conversation de base en langue fe'efe'e: Basic Conversation in Fe'efe'e Language": "nufi_conversation_de_base",
    "Conversations de base en langue fe'efe'e: Basic Conversation in Fe'efe'e Language": "nufi_conversation_de_base",
    "Conversations de base en langue basaa": "basaa_conversations_de_base",
    "Conversations de base en langue ghomala'": "ghomala_conversations_de_base",
    "Conversations de base en langue medumba": "medumba_conversations_de_base",
    "Conversations de base en langue ngemba": "ngemba_conversations_de_base",
    "Conversations de base en langue yemba": "yemba_conversations_de_base",
    "Ewondo Attic: Le Grenier de l'Ewondo: Akág Éwondo": "ewondo_attic",
    "Expressions idiomatiques en langue fe'efe'e (nufi)": "nufi_expressions_idiomatiques",
    "Expressions idiomatiques en langue fè'éfě'è (nùfī): Yū' mfèn pí yū' nkɑ̀ndàk mɑ̀ ghə̀ə̄ fè'éfě'è (nùfī)": "nufi_expressions_idiomatiques_extended",
    "French - Fulfulde - English Phrasebook: Guide de conversation trilingue français-anglais-fulfulde": "fulfulde_phrasebook",
    "Grammaire des langues bamilékés : Cas du nufi (fè'éfě'è): Sìēmbʉ́ɑ́ fè'éfě'è": "nufi_grammaire",
    "Guide de conversation (phrasebook) en langue ewondo - part I: Trilingual Phrasebook : French-English-Ewondo": "ewondo_phrasebook",
    "Guide de conversation (phrasebook) en langue fe'efe'e (nufi) - part I: Trilingual Phrasebook : French-English-Nufi": "nufi_phrasebook",
    "Guide de conversation trilingue Duala - Français - Anglais: Duala-French-English Phrasebook ": "duala_phrasebook",
    "Guide de conversation trilingue Français-Anglais- Shüpamom: French- Shüpǎmәm -English Phrasebook": "shupamom_phrasebook",
    "Guide de conversation trilingue Français-anglais-fe'efe'e.: French-Fè'éfě'è-English Phrasebook": "nufi_phrasebook_v2",
    "Guide de conversation trilingue Français-anglais-yemba (mise à jour).: French-Yemba-English Phrasebook": "yemba_phrasebook_updated",
    "Guide de conversation trilingue Français-anglais-éwé: French-Éwé-English Phrasebook": "ewe_phrasebook",
    "Guide de conversation trilingue Ghomala-Français-Anglais: Ŋwa'nyə msʉɔghɔm: Ghɔmálá'- French - English Phrasebook": "ghomala_phrasebook",
    "Guide de conversation trilingue Medumba-Français-anglais: Mə̀dʉ̂mbὰ-French-English Phrasebook": "medumba_phrasebook",
    "Guide de conversation trilingue Wolof-Français-Anglais: Wolof-French-English Phrasebook": "wolof_phrasebook",
    "Guide de conversation trilingue français-anglais-douala: French-Duala-English Phrasebook": "duala_phrasebook_v2",
    "Guide de conversation trilingue français-anglais-fulfulde: French - Fulfulde - English Phrasebook": "fulfulde_phrasebook_v2",
    "Guide de conversation trilingue français-anglais-medumba: French-Medumba-English Phrasebook": "medumba_phrasebook_v2",
    "Guide de conversation trilingue français-anglais-yemba: French-Yemba-English Phrasebook": "yemba_phrasebook",
    "Hausa - French - English Phrasebook: Guide de conversation Hausa-Français-Anglais.": "hausa_phrasebook",
    "Igbo - French - English Phrasebook: Guide de conversation Igbo-Français-Anglais. ": "igbo_phrasebook",
    "Kikongo (Kituba) - French - English Phrasebook: Guide de conversation Kikongo (Kituba)-Français-Anglais. ": "kikongo_phrasebook",
    "Kinyarwanda - French - English Phrasebook": "kinyarwanda_phrasebook",
    "Kiswahili's Attic - Darasa la Kiswahili: Le Grenier du Swahili": "kiswahili_attic",
    "La fourmi affamée : Basaa-Français: Njàl ì gwèe Sulûk": "basaa_fourmi_affamée",
    "La fourmi affamée : Dioula-Français: Dugumɛnɛ kɔngɔtɔ": "dioula_fourmi_affamée",
    "La fourmi affamée : Duala-Français: Sɔnɔ́ na njai": "duala_fourmi_affamée",
    "La fourmi affamée : Ewondo-Français.: Mǎn asɔ́sɔ̄n awóg zie": "ewondo_fourmi_affamée",
    "La fourmi affamée : Fongbe-Français": "fongbe_fourmi_affamée",
    "La fourmi affamée : Ghomala-Français: Jikǔʼ wə́ jɛ́ títyə́": "ghomala_fourmi_affamée",
    "La fourmi affamée : Medumba-Français: Nzìkû' cwɛ̌d nja ndèdndèd.": "medumba_fourmi_affamée",
    "La fourmi affamée : Nufi-Français: Nzhìèkǔ' mɑ̀nkō ngʉ́ngà'": "nufi_fourmi_affamée",
    "La fourmi affamée : Wolof-Français: Melentaan wu xiif": "wolof_fourmi_affamée",
    "La fourmi affamée : Yemba-Français: Nzií sī nzāŋà kīkyā": "yemba_fourmi_affamée",
    "La fourmi affamée : Ŋgə̂mbà – Français: Tə́ttá pfʉ́ njjikhwu'ú": "ngemba_fourmi_affamée",
    "La grammaire des langues bamilekes : cas du nufi": "nufi_grammaire_v1",
    "Le Grenier du Ghomala: Ntɛ̂ GhɔmáláꞋ, GhɔmáláꞋ Attic ": "ghomala_attic",
    "Le Grenier du Hausa : Hausa Attic": "hausa_attic",
    "Le Grenier du Medumba: Ntà Mə̀dʉ̂mbὰ, Mə̀dʉ̂mbὰ Attic  ": "medumba_attic",
    "Le Grenier du Nguemba: Ntâŋ Ŋgə̂mbà : Ngemba Attic": "ngemba_attic",
    "Le Grenier du Shupamom : Shupamom Attic ": "shupamom_attic",
    "Le Grenier du Yemba": "yemba_attic",
    "Lingala - French - English Phrasebook: Guide de conversation Lingala-Français-Anglais.": "lingala_phrasebook",
    "Mon prénom africain, mon prénom bamiléké: Pour la revalorisation et la réintégration des anthroponymes Africains": "prénom_africain_bamiléké",
    "NO MORE WESTERN NAMES! For African Kids": "no_more_western_names",
    "Ntǎ' Nùfī - Nùfī Attic - Le Grenier du Nùfī": "nufi_attic",
    "Nùfī Attic - Le Grenier du Nùfī - KAM 1: Ntǎ' Nùfī ": "nufi_attic_kam",
    "Nùfī Attic - Le Grenier du Nùfī - KAM 2: Ntǎ' Nùfī ": "nufi_attic_kam",
    "Nùfī Attic - Le Grenier du Nùfī - KAM 3: Ntǎ' Nùfī": "nufi_attic_kam",
    "Nùfī Attic - Le Grenier du Nùfī - KAM 4: Ntǎ' Nùfī ": "nufi_attic_kam",
    "Nùfī Attic - Le Grenier du Nùfī - KAM 5: Ntǎ' Nùfī ": "nufi_attic_kam",
    "Nùfī Attic - Le Grenier du Nùfī - KAM 6: Ntǎ' Nùfī ": "nufi_attic_kam",
    "Saaq Wolof: Wolof Attic: Le Grenier du Wolof": "wolof_attic",
    "Swahili Fairy Tales : Work today and eat tomorrow  be lazy today and steal tomorrow: Translated From Bamileke Tale": "swahili_conte_travaille_paresse",
    "Swahili-French-English Phrasebook: Guide de conversation trilingue Swahili-Français-Anglais": "swahili_phrasebook",
    "Syllabaire et Dictionnaire Visuel en langue fe'efe'e: Nkǔnjâ'wū pí mbíághəə": "nufi_syllabaire",
    "Syllabaire et dictionnaire visuel en langue ewondo": "ewondo_syllabaire",
    "Tshiluba - French - English Phrasebook: Guide de conversation Tshiluba-Français-Anglais. ": "tshiluba_phrasebook",
    "Tshiluba Attic: Le Grenier du Tshiluba: Kahala kaTshiluba: Le Grenier du Tshiluba: Kahala kaTshiluba": "tshiluba_attic",
    "Twi- French - English Phrasebook: Kasa Mmiɛnsa Nkɔmmɔbɔ Akwankyerɛ": "twi_phrasebook",
    "Yoruba - French - English Phrasebook: Guide de conversation Yoruba – Français - Anglais": "yoruba_phrasebook",
    "Zulu - French - English Phrasebook: Guide de conversation trilingue IsiZulu – Français - Anglais": "zulu_phrasebook",
    "Étude Comparative des Variantes Dialectales de L'unique Langue Bamiléké Part I: Comparative Study of the Bamileke dialects Part I": "bamileke_étude_comparative",
}

# Mapping from database book_nick_name to royalty book_nick_name(s)
# This bridges the gap between long descriptive DB nicknames and short royalty nicknames
DB_NICKNAME_TO_ROYALTY = {
    # Phrasebooks
    "nufi_phrasebook_guide_conversation_trilingue": ["nufi_phrasebook", "nufi_phrasebook_v2"],
    "ewondo_phrasebook_guide_conversation_trilingue": ["ewondo_phrasebook"],
    "duala_phrasebook_guide_conversation_trilingue": ["duala_phrasebook", "duala_phrasebook_v2"],
    "medumba_phrasebook_guide_conversation_trilingue": ["medumba_phrasebook", "medumba_phrasebook_v2"],
    "yemba_phrasebook_guide_conversation_trilingue": ["yemba_phrasebook", "yemba_phrasebook_updated"],
    "wolof_phrasebook_guide_conversation_trilingue": ["wolof_phrasebook"],
    "swahili_phrasebook_guide_conversation_trilingue": ["swahili_phrasebook"],
    "shupamom_phrasebook_guide_conversation_trilingue": ["shupamom_phrasebook"],
    "ewe_phrasebook_guide_conversation_trilingue": ["ewe_phrasebook"],
    "hausa_phrasebook_guide_conversation_trilingue": ["hausa_phrasebook"],
    "yoruba_phrasebook_guide_conversation_trilingue": ["yoruba_phrasebook"],
    "lingala_phrasebook_guide_conversation_trilingue": ["lingala_phrasebook"],
    "tshiluba_phrasebook_guide_conversation_trilingue": ["tshiluba_phrasebook"],
    "igbo_phrasebook_guide_conversation_trilingue": ["igbo_phrasebook"],
    "kinyarwanda_phrasebook_guide_conversation_trilingue": ["kinyarwanda_phrasebook"],
    "basaa_phrasebook_guide_conversation_trilingue": ["basaa_phrasebook"],
    "chichewa_phrasebook_guide_conversation_trilingue": ["chichewa_phrasebook"],
    "ghomala_phrasebook_guide_conversation_trilingue": ["ghomala_phrasebook"],
    "zulu_phrasebook_guide_conversation_trilingue": ["zulu_phrasebook"],
    "twi_phrasebook_guide_conversation_trilingue": ["twi_phrasebook"],
    "kikongo-kituba_phrasebook_guide_conversation_trilingue": ["kikongo_phrasebook"],
    "fulfulde-nigeria-cameroun_phrasebook_guide_conversation_trilingue": ["fulfulde_phrasebook", "fulfulde_phrasebook_v2"],
    "fulfulde-benin-niger-mali_phrasebook_guide_conversation_trilingue": ["fulfulde_phrasebook", "fulfulde_phrasebook_v2"],
    
    # Attic / Grenier books
    "nufi_attic_grenier": ["nufi_attic", "nufi_attic_kam"],
    "ngemba_attic_grenier": ["ngemba_attic"],
    "yemba_attic_grenier": ["yemba_attic"],
    "medumba_attic_grenier": ["medumba_attic"],
    "ghomala_attic_grenier": ["ghomala_attic"],
    "basaa_attic_grenier": ["basaa_attic"],
    "duala_attic_grenier": ["duala_attic"],
    "ewondo_attic_grenier": ["ewondo_attic"],
    "wolof_attic_grenier": ["wolof_attic"],
    "hausa_attic_grenier": ["hausa_attic"],
    "yoruba_attic_grenier": ["yoruba_attic"],
    "igbo_attic_grenier": ["igbo_attic"],
    "tshiluba_attic_grenier": ["tshiluba_attic"],
    "shupamom_attic_grenier": ["shupamom_attic"],
    "kiswahili_attic_grenier": ["kiswahili_attic"],
    "fulfulde_attic_grenier": ["fulfulde_attic"],
    
    # Fairy Tales - Contes
    "english-french_african_tales_bamiléké_fairy_tales": ["english-french_african_tales"],
    "english-french_bamilekes_fairy_work_value": ["english-french_bamilekes_fairy_tales"],
    "nufi_contes_africains_contes_bamilekés_hard_cover": ["nufi_contes_bamilekés_couleur", "nufi_contes_bamilekés_black_white", "nufi_contes_bamilekés_RETIRED"],
    "nufi_travaille_paresse": ["nufi_conte_travaille_paresse"],
    "medumba_travaille_paresse": ["medumba_conte_travaille_paresse"],
    "yemba_travaille_paresse": ["yemba_conte_travaille_paresse"],
    "wolof_travaille_paresse": ["wolof_conte_travaille_paresse"],
    "kikongo_travaille_paresse": ["kikongo_conte_travaille_paresse"],
    "swahili_travaille_paresse": ["swahili_conte_travaille_paresse"],
    "ngiemboon_travaille_paresse": ["ngiemboon_conte_travaille_paresse"],
    
    # Comparative study
    "bamileke_étude_comparative_mulb": ["bamileke_étude_comparative"],
    
    # Names
    "mon_prénom_africain_mon_prénom_bamiléké": ["prénom_africain_bamiléké"],
    
    # Conversation de base (ewondo special case)
    "ewondo_conversation_de_base": ["Conversations de base en langue ewondo"],
}
